/* ===========================================================
   FERNWOOD ANIMAL HOSPITAL — script.js
   -----------------------------------------------------------
   Content-heavy sections and singleton copy blocks load from
   data/*.json at runtime. Those files are generated by
   scripts/build-content.js from the Decap CMS content/ folder
   on every Netlify deploy, so staff edits made through /admin
   show up here with no code changes.

   If a fetch fails — e.g. opening index.html directly via
   file://, or before the very first Netlify build — everything
   falls back to the FALLBACK constant below, which mirrors the
   seed content exactly. Nothing is ever left blank.
   =========================================================== */

const FALLBACK = {
  site: {
    name: "Fernwood Animal Hospital",
    phone: "(555) 019-8142",
    phoneHref: "+15550142",
    emergencyPhone: "(555) 019-9911",
    emergencyPhoneHref: "+15550199",
    email: "hello@fernwoodanimalhospital.example",
    address: "482 Willowmere Lane, Cedar Falls, CA 94582",
    hours: "Mon–Fri 7:30am–7pm · Sat 8am–5pm · Sun 9am–2pm",
    parking: "Free lot parking behind the building, wheelchair accessible",
    mapEmbedUrl: "https://www.google.com/maps?q=San+Francisco+Bay+Area&output=embed",
    whatsapp: "https://wa.me/15550142",
    social: { facebook: "#", instagram: "#", tiktok: "#", youtube: "#" },
    footerBlurb: "Compassionate, advanced veterinary care for every paw, feather, and fur since 2011."
  },

  hero: {
    eyebrow: "Fernwood Animal Hospital · Est. 2011",
    headline: "Compassionate Care for Every Paw, Feather, and Fur",
    subheadline: "Providing exceptional veterinary care with advanced medical technology and a loving touch for every pet — from routine wellness visits to emergency medicine.",
    primaryCtaLabel: "Book an Appointment",
    emergencyCtaLabel: "Emergency Contact",
    trustBadges: [
      { icon: "fa-shield-heart", text: "Fear-Free Certified" },
      { icon: "fa-star", text: "4.9/5 from 2,300+ reviews" },
      { icon: "fa-clock", text: "Open 7 days a week" }
    ],
    images: {
      main: { src: "https://plus.unsplash.com/premium_photo-1661916447474-235409b19e16?auto=format&fit=crop&w=900&q=80", alt: "Veterinarian gently holding a small dog on the exam table" },
      secondary: { src: "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=600&q=80", alt: "Smiling pet owner holding her tabby cat" }
    },
    stats: [
      { value: "12,400+", label: "Happy pets treated" },
      { value: "14 yrs", label: "Avg. vet experience" }
    ]
  },

  about: {
    eyebrow: "About Fernwood",
    heading: "Fifteen years of gentle, advanced care",
    body: "Fernwood Animal Hospital opened in 2011 with a simple belief: outstanding medicine and genuine warmth aren't a trade-off. Today our AAHA-accredited hospital blends digital diagnostics, in-house surgery and dentistry, and a fear-free approach with the kind of unhurried attention every pet — and every pet parent — deserves.",
    mission: { title: "Mission", text: "Deliver compassionate, evidence-based care that keeps pets healthy at every life stage." },
    vision: { title: "Vision", text: "Be the most trusted animal hospital in the region — for pets, and the people who love them." },
    values: { title: "Values", text: "Empathy first, honest communication, and never rushing a decision that matters." },
    counters: [
      { target: 12400, label: "Happy Pets" },
      { target: 15, label: "Years of Service" },
      { target: 9800, label: "Successful Treatments" },
      { target: 98, label: "% Client Satisfaction" }
    ],
    images: {
      a: { src: "https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=700&q=80", alt: "Bright, modern veterinary clinic interior" },
      b: { src: "https://plus.unsplash.com/premium_photo-1663039950073-187c977da2e9?auto=format&fit=crop&w=600&q=80", alt: "Veterinarian using a stethoscope on a puppy in the consultation room" },
      c: { src: "https://plus.unsplash.com/premium_photo-1661962620229-614e281fe009?auto=format&fit=crop&w=600&q=80", alt: "Two veterinary staff members carefully treating a small dog" }
    }
  },

  sectionHeadings: {
    doctors:      { eyebrow: "Meet the Team", heading: "Meet Our Veterinarians", subtext: "Board-certified, endlessly patient, and just as obsessed with your pet as you are." },
    services:     { eyebrow: "What We Treat", heading: "Comprehensive Veterinary Services", subtext: "From first puppy visit to golden years, one team follows your pet through every stage." },
    whyUs:        { eyebrow: "Why Fernwood", heading: "Why Pet Parents Choose Us", subtext: "" },
    wellness:     { eyebrow: "Wellness Membership", heading: "Pet Wellness Programs", subtext: "Predictable monthly pricing that bundles the care every pet needs, with no surprise bills." },
    gallery:      { eyebrow: "Life at Fernwood", heading: "Gallery", subtext: "" },
    testimonials: { eyebrow: "Client Stories", heading: "What Pet Parents Say", subtext: "" },
    booking:      { eyebrow: "Book a Visit", heading: "Schedule Your Pet's Appointment", subtext: "Tell us about your pet and pick a time that works. Our care team confirms every request within one business hour." },
    tips:         { eyebrow: "Pet Parent Library", heading: "Pet Care Tips", subtext: "" },
    facilities:   { eyebrow: "Behind the Scenes", heading: "Our Facilities & Standards", subtext: "Modern equipment, rigorous infection control, and a hospital that's spotless from the lobby to the surgery suite." },
    faq:          { eyebrow: "Good to Know", heading: "Frequently Asked Questions", subtext: "" },
    contact:      { eyebrow: "Visit Us", heading: "Contact Fernwood Animal Hospital", subtext: "" }
  },

  community: {
    eyebrow: "Beyond the Clinic",
    heading: "Adoption & Community",
    body: "We believe a healthier community starts outside our doors too. Fernwood partners with local shelters and hosts free educational events year-round.",
    items: [
      { icon: "fa-house-heart", text: "Monthly pet adoption events with Cedar Falls Animal Rescue" },
      { icon: "fa-hands-holding-child", text: "Ongoing partnerships with 3 regional rescue organizations" },
      { icon: "fa-chalkboard-user", text: "Free pet education seminars, open to the public" },
      { icon: "fa-hand-holding-dollar", text: "Charity care fund for families facing hardship" }
    ],
    ctaLabel: "Partner With Us",
    image: { src: "https://images.unsplash.com/photo-1700665537604-412e89a285c3?auto=format&fit=crop&w=800&q=80", alt: "A family sitting together with their dog, part of a community adoption event" }
  },

  emergency: {
    eyebrowText: "Urgent Care",
    heading: "Emergency & After-Hours Care",
    body: "If your pet is in crisis, call us immediately — day or night. Our team will guide you through what to do before you arrive.",
    hoursNote: "After-hours & holidays: 24/7 emergency line staffed",
    steps: [
      "Call ahead so our team can prepare for your pet's condition.",
      "Keep your pet warm, calm, and as still as safely possible.",
      "Do not give food, water, or medication unless instructed.",
      "Bring any medications or toxins your pet may have ingested."
    ],
    ctaLabel: "Call Emergency Line Now"
  },

  vets: [
    { name: 'Dr. Maya Alvarez', title: 'Lead Veterinarian & Medical Director', qual: 'DVM, University of California Davis', years: 16, expertise: 'Internal medicine, soft-tissue surgery', interests: 'Senior pet care, diagnostics', photo: 'https://plus.unsplash.com/premium_photo-1661916447474-235409b19e16?auto=format&fit=crop&w=600&q=80' },
    { name: 'Dr. Owen Bennett', title: 'Associate Veterinarian', qual: 'DVM, Cornell University', years: 9, expertise: 'Orthopedic surgery, sports medicine', interests: 'Working & performance dogs', photo: 'https://images.unsplash.com/photo-1637059824899-a441006a6875?auto=format&fit=crop&w=600&q=80' },
    { name: 'Dr. Priya Nair', title: 'Feline & Exotic Specialist', qual: 'DVM, DACVIM (Feline Practice)', years: 12, expertise: 'Feline medicine, exotic & pocket pets', interests: 'Dermatology, nutrition', photo: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=600&q=80' },
    { name: 'Dr. Samuel Ortiz', title: 'Emergency & Critical Care', qual: 'DVM, DACVECC', years: 11, expertise: 'Emergency medicine, toxicology', interests: 'Trauma stabilization', photo: 'https://images.unsplash.com/photo-1673865641073-4479f93a7776?auto=format&fit=crop&w=600&q=80' }
  ],

  services: [
    { icon:'fa-stethoscope', name:'Wellness Exams', desc:'Nose-to-tail checkups that catch problems early.' },
    { icon:'fa-syringe', name:'Vaccinations', desc:'Core and lifestyle vaccines tailored to your pet.' },
    { icon:'fa-paw', name:'Puppy & Kitten Care', desc:'A gentle start: first exams, deworming, and guidance.' },
    { icon:'fa-shield-heart', name:'Preventive Healthcare', desc:'Screenings and plans that keep small issues small.' },
    { icon:'fa-tooth', name:'Dental Care', desc:'Cleanings, extractions, and at-home dental coaching.' },
    { icon:'fa-scissors', name:'Pet Grooming', desc:'Bathing, trims, and nail care in a calm, fear-free space.' },
    { icon:'fa-kit-medical', name:'Pet Surgery', desc:'Soft-tissue and orthopedic surgery with in-house recovery.' },
    { icon:'fa-heart-pulse', name:'Spay & Neuter', desc:'Safe, routine procedures with same-day discharge.' },
    { icon:'fa-truck-medical', name:'Emergency Care', desc:'Urgent treatment when your pet needs it most.' },
    { icon:'fa-vial', name:'Laboratory Testing', desc:'In-house bloodwork and diagnostics with fast results.' },
    { icon:'fa-x-ray', name:'Digital X-Rays', desc:'High-resolution imaging read the same day.' },
    { icon:'fa-wave-square', name:'Ultrasound', desc:'Non-invasive imaging for soft tissue and pregnancy.' },
    { icon:'fa-microchip', name:'Microchipping', desc:'Permanent ID that reunites lost pets with families.' },
    { icon:'fa-bug', name:'Parasite Prevention', desc:'Heartworm, intestinal parasite testing and prevention.' },
    { icon:'fa-bug-slash', name:'Flea & Tick Treatment', desc:'Year-round protection plans for every climate.' },
    { icon:'fa-bowl-food', name:'Nutrition Counseling', desc:'Diet plans for weight, allergies, and life stage.' },
    { icon:'fa-heart-circle-plus', name:'Senior Pet Care', desc:'Extra support for aging joints, organs, and minds.' },
    { icon:'fa-notes-medical', name:'Dermatology', desc:'Relief for allergies, hot spots, and chronic skin issues.' },
    { icon:'fa-bone', name:'Orthopedic Care', desc:'ACL repair, fracture care, and mobility support.' },
    { icon:'fa-feather', name:'Exotic Pet Care', desc:'Birds, reptiles, and small mammals welcome.' },
    { icon:'fa-passport', name:'Pet Travel Certificates', desc:'Health certificates for domestic and international travel.' },
    { icon:'fa-hand-holding-heart', name:'End-of-Life Care', desc:'Gentle, dignified support for pets and families.' }
  ],

  whyUs: [
    { icon:'fa-hand-holding-heart', title:'Compassionate Team' },
    { icon:'fa-x-ray', title:'Modern Equipment' },
    { icon:'fa-microscope', title:'Advanced Diagnostics' },
    { icon:'fa-truck-medical', title:'Emergency Services' },
    { icon:'fa-dove', title:'Fear-Free Handling' },
    { icon:'fa-clipboard-list', title:'Personalized Plans' },
    { icon:'fa-tags', title:'Affordable Wellness' },
    { icon:'fa-user-doctor', title:'Experienced Specialists' },
    { icon:'fa-broom', title:'Clean & Safe Space' },
    { icon:'fa-calendar-check', title:'Easy Scheduling' }
  ],

  wellnessPlans: [
    { name:'Puppy Wellness', icon:'fa-paw', price:39, feats:['3 wellness visits','Core vaccine series','Free deworming'] },
    { name:'Kitten Wellness', icon:'fa-cat', price:35, feats:['3 wellness visits','FVRCP + rabies series','Free deworming'] },
    { name:'Annual Preventive', icon:'fa-shield-heart', price:29, feats:['1 annual exam','Bloodwork panel','Parasite screening'], featured:true },
    { name:'Senior Wellness', icon:'fa-heart-circle-plus', price:45, feats:['2 exams / year','Senior bloodwork','Joint & organ screening'] },
    { name:'Vaccination Package', icon:'fa-syringe', price:19, feats:['All core vaccines','Annual boosters','Digital records'] },
    { name:'Dental Care Plan', icon:'fa-tooth', price:25, feats:['Annual cleaning','10% off dental work','At-home care kit'] }
  ],

  gallery: [
    { cat:'pets', img:'https://images.unsplash.com/photo-1630438994394-3deff7a591bf?auto=format&fit=crop&w=500&q=80', caption:'A happy patient after checkup' },
    { cat:'pets', img:'https://images.unsplash.com/photo-1621371236495-1520d8dc72a5?auto=format&fit=crop&w=500&q=80', caption:'Feeling great and full of energy' },
    { cat:'team', img:'https://plus.unsplash.com/premium_photo-1663039950073-187c977da2e9?auto=format&fit=crop&w=500&q=80', caption:'Our team at work' },
    { cat:'facilities', img:'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=500&q=80', caption:'Reception & waiting lounge' },
    { cat:'grooming', img:'https://images.unsplash.com/photo-1577175889968-f551f5944abd?auto=format&fit=crop&w=500&q=80', caption:'Fresh from the grooming studio' },
    { cat:'surgery', img:'https://plus.unsplash.com/premium_photo-1661942274165-00cc8d55a93f?auto=format&fit=crop&w=500&q=80', caption:'Careful surgery preparation' },
    { cat:'pets', img:'https://images.unsplash.com/photo-1596272875729-ed2ff7d6d9c5?auto=format&fit=crop&w=500&q=80', caption:'Feline friend paying a visit' },
    { cat:'pets', img:'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=500&q=80', caption:'Owner and cat, all smiles' },
    { cat:'diagnostics', img:'https://plus.unsplash.com/premium_photo-1661954422066-36639b6f13b5?auto=format&fit=crop&w=500&q=80', caption:'Listening carefully to every heartbeat' },
    { cat:'pets', img:'https://images.unsplash.com/photo-1725409796872-8b41e8eca929?auto=format&fit=crop&w=500&q=80', caption:'Kitten check-up day' },
    { cat:'community', img:'https://images.unsplash.com/photo-1700665537604-412e89a285c3?auto=format&fit=crop&w=500&q=80', caption:'Family adoption day' },
    { cat:'surgery', img:'https://plus.unsplash.com/premium_photo-1661962620229-614e281fe009?auto=format&fit=crop&w=500&q=80', caption:'Gentle post-op care' },
    { cat:'pets', img:'https://images.unsplash.com/photo-1630359486912-4b085e38f1e7?auto=format&fit=crop&w=500&q=80', caption:'A very good boy' },
    { cat:'pets', img:'https://images.unsplash.com/photo-1553688738-a278b9f063e0?auto=format&fit=crop&w=500&q=80', caption:'Puppy waiting room manners' },
    { cat:'grooming', img:'https://images.unsplash.com/photo-1710322928695-c7fb49886cb1?auto=format&fit=crop&w=500&q=80', caption:'Pampered and polished' },
    { cat:'team', img:'https://images.unsplash.com/photo-1770836037816-4445dbd449fd?auto=format&fit=crop&w=500&q=80', caption:'Dental check for a curious patient' }
  ],

  testimonials: [
    { name:'Maria D.', pet:'Bruno · Labrador Retriever', rating:5, story:"Our Labrador received outstanding care after his surgery — the team called to check on him for a week straight.", photo:'https://images.unsplash.com/photo-1700665537604-412e89a285c3?auto=format&fit=crop&w=300&q=80' },
    { name:'James K.', pet:'Whiskers · Domestic Shorthair', rating:5, story:"They treated our cat like family from the very first visit. I finally found a vet I trust completely.", photo:'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=300&q=80' },
    { name:'Aisha R.', pet:'Coco · French Bulldog', rating:5, story:"Highly recommended for emergency services — they took Coco in at 11pm without hesitation and saved her life.", photo:'https://images.unsplash.com/photo-1630359486912-4b085e38f1e7?auto=format&fit=crop&w=300&q=80' },
    { name:'Daniel P.', pet:'Mittens · Kitten', rating:5, story:"Gentlest hands I've ever seen with a scared kitten. Mittens actually purred through her whole exam.", photo:'https://images.unsplash.com/photo-1728013274420-ed02b1f58887?auto=format&fit=crop&w=300&q=80' },
    { name:'Priya S.', pet:'Rosie · Golden Retriever mix', rating:5, story:"The wellness plan has genuinely saved us money, and Rosie's checkups are actually something she looks forward to.", photo:'https://images.unsplash.com/photo-1630438994394-3deff7a591bf?auto=format&fit=crop&w=300&q=80' },
    { name:'Tom H.', pet:'Leo · Senior Terrier mix', rating:5, story:"Dr. Alvarez talked us through every option for Leo's arthritis with so much patience. No pressure, just honesty.", photo:'https://images.unsplash.com/photo-1700665537650-1bf37979aae0?auto=format&fit=crop&w=300&q=80' }
  ],

  tips: [
    { icon:'fa-calendar-check', tag:'Wellness', title:'How Often Should My Pet Visit the Vet?', excerpt:'A simple age-by-age guide to checkup frequency, from playful puppy to golden years.' },
    { icon:'fa-syringe', tag:'Prevention', title:'Vaccination Schedule Explained', excerpt:'What core and lifestyle vaccines do, and when your pet actually needs them.' },
    { icon:'fa-triangle-exclamation', tag:'Emergency', title:'Signs Your Pet Needs Immediate Care', excerpt:'The red-flag symptoms that mean "call now," not "wait and see."' },
    { icon:'fa-bowl-food', tag:'Nutrition', title:'Nutrition Tips for Every Life Stage', excerpt:'How to read a pet food label and avoid the most common feeding mistakes.' },
    { icon:'fa-tooth', tag:'Dental', title:'Dental Health for Pets', excerpt:'Why 80% of pets have dental disease by age three — and how to prevent it.' },
    { icon:'fa-bug-slash', tag:'Prevention', title:'Flea & Tick Prevention 101', excerpt:'Year-round protection tips for every season and every climate.' }
  ],

  faq: [
    { q:'Do you accept walk-ins?', a:'Yes — we hold same-day slots for urgent concerns, though scheduled appointments are seen first. Call ahead when you can so we can prepare.' },
    { q:'What pets do you treat?', a:'Dogs, cats, rabbits, birds, and most small mammals and reptiles. Our exotic pet specialist can advise on less common species — just ask.' },
    { q:'Do you offer emergency services?', a:'Yes, our emergency line is staffed 24/7, including holidays. Call (555) 019-9911 before arriving whenever possible.' },
    { q:'How often should pets be vaccinated?', a:'Core vaccines are typically boosted annually or every three years depending on the vaccine; your vet will build a schedule around your pet\'s lifestyle and risk.' },
    { q:'Do you perform surgeries?', a:'Yes — from routine spay/neuter to orthopedic and soft-tissue procedures, all with in-house monitored recovery.' },
    { q:'How should I prepare for my appointment?', a:'Bring any medications, prior records, and a list of questions. For surgery, we\'ll send fasting instructions ahead of time.' }
  ],

  awards: [
    { icon:'fa-award', text:'AAHA Accredited Hospital' },
    { icon:'fa-shield-heart', text:'Fear Free Certified Practice' },
    { icon:'fa-trophy', text:'Best Animal Hospital — Cedar Falls Paws Awards' },
    { icon:'fa-leaf', text:'Certified Green Business' }
  ]
};

const tourStops = [
  { img:'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=1000&q=80', caption:'Reception & Waiting Lounge' },
  { img:'https://plus.unsplash.com/premium_photo-1663039950073-187c977da2e9?auto=format&fit=crop&w=1000&q=80', caption:'Consultation Room' },
  { img:'https://plus.unsplash.com/premium_photo-1661942274165-00cc8d55a93f?auto=format&fit=crop&w=1000&q=80', caption:'Surgery Suite' },
  { img:'https://images.unsplash.com/photo-1577175889968-f551f5944abd?auto=format&fit=crop&w=1000&q=80', caption:'Grooming Studio' },
  { img:'https://plus.unsplash.com/premium_photo-1661962620229-614e281fe009?auto=format&fit=crop&w=1000&q=80', caption:'Recovery Area' }
];

/* =========================================================
   FETCH + FALLBACK
   ========================================================= */

async function fetchJSON(relPath) {
  try {
    const res = await fetch(relPath, { cache: 'no-store' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  } catch (err) {
    return null; // silently fall back — this is expected when opened via file:// or pre-first-build
  }
}

async function loadSiteContent() {
  const files = [
    'data/site.json', 'data/hero.json', 'data/about.json', 'data/community.json',
    'data/emergency.json', 'data/section-headings.json', 'data/vets.json',
    'data/services.json', 'data/why-us.json', 'data/wellness-plans.json',
    'data/gallery.json', 'data/testimonials.json', 'data/tips.json',
    'data/faq.json', 'data/awards.json'
  ];
  const results = await Promise.all(files.map(fetchJSON));
  const [site, hero, about, community, emergency, sectionHeadings,
         vets, services, whyUs, wellnessPlans, gallery, testimonials, tips, faq, awards] = results;

  const useArr = (val, fallback) => (Array.isArray(val) && val.length) ? val : fallback;

  return {
    site: site || FALLBACK.site,
    hero: hero || FALLBACK.hero,
    about: about || FALLBACK.about,
    community: community || FALLBACK.community,
    emergency: emergency || FALLBACK.emergency,
    sectionHeadings: sectionHeadings || FALLBACK.sectionHeadings,
    vets: useArr(vets, FALLBACK.vets),
    services: useArr(services, FALLBACK.services),
    whyUs: useArr(whyUs, FALLBACK.whyUs),
    wellnessPlans: useArr(wellnessPlans, FALLBACK.wellnessPlans),
    gallery: useArr(gallery, FALLBACK.gallery),
    testimonials: useArr(testimonials, FALLBACK.testimonials),
    tips: useArr(tips, FALLBACK.tips),
    faq: useArr(faq, FALLBACK.faq),
    awards: useArr(awards, FALLBACK.awards)
  };
}

/* =========================================================
   RENDER: SINGLETON COPY BLOCKS
   ========================================================= */

function setText(id, text) {
  const el = document.getElementById(id);
  if (el && text != null) el.textContent = text;
}

function renderHero(hero) {
  setText('heroEyebrow', hero.eyebrow);
  setText('heroHeadline', hero.headline);
  setText('heroSubheadline', hero.subheadline);
  setText('heroPrimaryCtaLabel', hero.primaryCtaLabel);
  setText('heroEmergencyCtaLabel', hero.emergencyCtaLabel);

  const trustEl = document.getElementById('heroTrust');
  if (trustEl && Array.isArray(hero.trustBadges)) {
    trustEl.innerHTML = hero.trustBadges.map(b =>
      `<div class="trust-item"><i class="fa-solid ${b.icon}"></i> ${b.text}</div>`
    ).join('');
  }

  const imgMain = document.getElementById('heroImgMain');
  if (imgMain && hero.images && hero.images.main) {
    imgMain.src = hero.images.main.src;
    imgMain.alt = hero.images.main.alt;
  }
  const imgSecondary = document.getElementById('heroImgSecondary');
  if (imgSecondary && hero.images && hero.images.secondary) {
    imgSecondary.src = hero.images.secondary.src;
    imgSecondary.alt = hero.images.secondary.alt;
  }

  if (Array.isArray(hero.stats)) {
    if (hero.stats[0]) { setText('heroStat1Value', hero.stats[0].value); setText('heroStat1Label', hero.stats[0].label); }
    if (hero.stats[1]) { setText('heroStat2Value', hero.stats[1].value); setText('heroStat2Label', hero.stats[1].label); }
  }
}

function renderAbout(about) {
  setText('aboutEyebrow', about.eyebrow);
  setText('aboutHeading', about.heading);
  setText('aboutBody', about.body);
  if (about.mission) { setText('missionTitle', about.mission.title); setText('missionText', about.mission.text); }
  if (about.vision) { setText('visionTitle', about.vision.title); setText('visionText', about.vision.text); }
  if (about.values) { setText('valuesTitle', about.values.title); setText('valuesText', about.values.text); }

  const imgs = about.images || {};
  const map = { aboutImgA: imgs.a, aboutImgB: imgs.b, aboutImgC: imgs.c };
  Object.entries(map).forEach(([id, img]) => {
    if (!img) return;
    const el = document.getElementById(id);
    if (el) { el.src = img.src; el.alt = img.alt; }
  });

  const countersEl = document.getElementById('counters');
  if (countersEl && Array.isArray(about.counters)) {
    countersEl.innerHTML = about.counters.map(c => `
      <div class="counter"><span class="counter-num" data-target="${c.target}">0</span><span class="counter-label">${c.label}</span></div>
    `).join('');
  }
}

function renderSectionHeadings(headings) {
  Object.entries(headings || {}).forEach(([key, h]) => {
    const container = document.querySelector(`[data-section-heading="${key}"]`);
    if (!container) return;
    const eyebrowEl = container.querySelector('.eyebrow');
    const h2El = container.querySelector('h2');
    const pEl = container.querySelector('p');
    if (eyebrowEl && h.eyebrow != null) eyebrowEl.textContent = h.eyebrow;
    if (h2El && h.heading != null) h2El.textContent = h.heading;
    if (pEl && h.subtext) pEl.textContent = h.subtext;
  });
}

function renderCommunity(community) {
  setText('communityEyebrow', community.eyebrow);
  setText('communityHeading', community.heading);
  setText('communityBody', community.body);
  setText('communityCta', community.ctaLabel);

  const listEl = document.getElementById('communityList');
  if (listEl && Array.isArray(community.items)) {
    listEl.innerHTML = community.items.map(i => `<li><i class="fa-solid ${i.icon}"></i> ${i.text}</li>`).join('');
  }

  const imgEl = document.getElementById('communityImage');
  if (imgEl && community.image) { imgEl.src = community.image.src; imgEl.alt = community.image.alt; }
}

function renderEmergency(emergency) {
  setText('emergencyEyebrowText', emergency.eyebrowText);
  setText('emergencyHeading', emergency.heading);
  setText('emergencyBody', emergency.body);
  setText('emergencyHoursNote', emergency.hoursNote);
  setText('emergencyCtaLabel', emergency.ctaLabel);

  const stepsEl = document.getElementById('emergencySteps');
  if (stepsEl && Array.isArray(emergency.steps)) {
    stepsEl.innerHTML = emergency.steps.map(s => `<li>${s}</li>`).join('');
  }
}

function renderSiteSettings(site) {
  const setHref = (sel, href) => document.querySelectorAll(sel).forEach(el => el.href = href);
  const setTxt = (sel, text) => document.querySelectorAll(sel).forEach(el => el.textContent = text);

  if (site.phoneHref) setHref('[data-role="phone-link"]', 'tel:' + site.phoneHref);
  if (site.phone) setTxt('[data-role="phone-text"]', site.phone);
  if (site.emergencyPhoneHref) setHref('[data-role="emergency-link"]', 'tel:' + site.emergencyPhoneHref);
  if (site.emergencyPhone) setTxt('[data-role="emergency-text"]', site.emergencyPhone);
  if (site.email) { setHref('[data-role="email-link"]', 'mailto:' + site.email); setTxt('[data-role="email-text"]', site.email); }
  if (site.address) setTxt('[data-role="address-text"]', site.address);
  if (site.hours) setTxt('[data-role="hours-text"]', site.hours);
  if (site.parking) setTxt('[data-role="parking-text"]', site.parking);
  if (site.whatsapp) setHref('[data-role="whatsapp-link"]', site.whatsapp);
  if (site.mapEmbedUrl) document.querySelectorAll('[data-role="map-iframe"]').forEach(el => el.src = site.mapEmbedUrl);
  if (site.footerBlurb) setTxt('[data-role="footer-blurb"]', site.footerBlurb);

  Object.entries(site.social || {}).forEach(([key, url]) => {
    if (url) setHref(`[data-social="${key}"]`, url);
  });
}

/* =========================================================
   BOOTSTRAP
   ========================================================= */

document.addEventListener('DOMContentLoaded', async () => {

  /* ---------- PAGE LOADER ---------- */
  const loader = document.getElementById('page-loader');
  window.addEventListener('load', () => {
    setTimeout(() => loader.classList.add('hidden'), 350);
  });
  setTimeout(() => loader && loader.classList.add('hidden'), 2500);

  /* ---------- AOS INIT ---------- */
  if (window.AOS) AOS.init({ duration: 700, once: true, offset: 60 });

  /* ---------- YEAR ---------- */
  const yearEl = document.getElementById('year');
  if (yearEl) yearEl.textContent = new Date().getFullYear();

  /* ---------- LOAD CONTENT (CMS data, with fallback) ---------- */
  const content = await loadSiteContent();

  /* ---------- RENDER SINGLETON COPY ----------
     Everything from here through the FAQ accordion is wrapped in a single
     try/catch: it all depends on fetched/fallback content, and one bad
     field should never be able to take down the rest of the page (nav,
     cookie banner, modals, chat widget, etc. are wired up unconditionally
     further down, outside this block). */
  try {
  renderHero(content.hero);
  renderAbout(content.about);
  renderSectionHeadings(content.sectionHeadings);
  renderCommunity(content.community);
  renderEmergency(content.emergency);
  renderSiteSettings(content.site);

  /* =========================================================
     RENDER: VETS
     ========================================================= */
  const vetGrid = document.getElementById('vetGrid');
  vetGrid.innerHTML = content.vets.map(v => `
    <div class="vet-card">
      <div class="vet-photo"><img src="${v.photo}" alt="Portrait of ${v.name}, ${v.title}" loading="lazy"></div>
      <div class="vet-body">
        <h3>${v.name}</h3>
        <div class="vet-title">${v.title}</div>
        <p>${v.qual} · ${v.years} yrs experience</p>
        <p><strong>Focus:</strong> ${v.expertise}</p>
        <div class="vet-meta"><span class="vet-tag">${v.interests}</span></div>
      </div>
    </div>
  `).join('');

  /* =========================================================
     RENDER: SERVICES
     ========================================================= */
  const servicesGrid = document.getElementById('servicesGrid');
  servicesGrid.innerHTML = content.services.map(s => `
    <div class="service-card" data-aos="fade-up">
      <div class="service-icon"><i class="fa-solid ${s.icon}"></i></div>
      <h3>${s.name}</h3>
      <p>${s.desc}</p>
      <a href="#booking" class="text-link">Learn More <i class="fa-solid fa-arrow-right"></i></a>
    </div>
  `).join('');

  /* =========================================================
     RENDER: WHY US
     ========================================================= */
  const whyGrid = document.getElementById('whyGrid');
  whyGrid.innerHTML = content.whyUs.map(w => `
    <div class="why-card" data-aos="fade-up">
      <i class="fa-solid ${w.icon}"></i>
      <h3>${w.title}</h3>
    </div>
  `).join('');

  /* =========================================================
     RENDER: WELLNESS PLANS
     ========================================================= */
  const wellnessGrid = document.getElementById('wellnessGrid');
  wellnessGrid.innerHTML = content.wellnessPlans.map(p => `
    <div class="wellness-card ${p.featured ? 'featured' : ''}" data-aos="fade-up">
      ${p.featured ? '<span class="wellness-badge">Most Popular</span>' : ''}
      <i class="fa-solid ${p.icon}"></i>
      <h3>${p.name}</h3>
      <div class="wellness-price">$${p.price}<span>/month</span></div>
      <ul>${p.feats.map(f => `<li><i class="fa-solid fa-check"></i> ${f}</li>`).join('')}</ul>
      <a href="#booking" class="btn ${p.featured ? 'btn-primary' : 'btn-outline'} btn-block btn-sm">Enroll Now</a>
    </div>
  `).join('');

  /* =========================================================
     RENDER: GALLERY + FILTERS
     ========================================================= */
  const galleryItems = content.gallery;
  const galleryFilters = document.getElementById('galleryFilters');
  const galleryGrid = document.getElementById('galleryGrid');
  const categories = ['all','pets','team','facilities','grooming','surgery','diagnostics','community'];
  const catLabels = { all:'All', pets:'Happy Pets', team:'Our Team', facilities:'Facilities', grooming:'Grooming', surgery:'Surgery & Recovery', diagnostics:'Diagnostics', community:'Community' };

  galleryFilters.innerHTML = categories.map((c,i) => `<button class="gallery-filter ${i===0 ? 'active' : ''}" data-cat="${c}">${catLabels[c]}</button>`).join('');

  galleryGrid.innerHTML = galleryItems.map((g,i) => `
    <div class="gallery-item" data-cat="${g.cat}" data-index="${i}">
      <img src="${g.img}" alt="${g.caption}" loading="lazy">
      <div class="gallery-caption">${g.caption}</div>
    </div>
  `).join('');

  galleryFilters.addEventListener('click', e => {
    const btn = e.target.closest('.gallery-filter');
    if (!btn) return;
    galleryFilters.querySelectorAll('.gallery-filter').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    const cat = btn.dataset.cat;
    document.querySelectorAll('.gallery-item').forEach(item => {
      item.classList.toggle('hide', cat !== 'all' && item.dataset.cat !== cat);
    });
  });

  /* ---------- LIGHTBOX ---------- */
  const lightbox = document.getElementById('lightbox');
  const lightboxImg = document.getElementById('lightboxImg');
  let currentGalleryIndex = 0;

  function openLightbox(index) {
    currentGalleryIndex = index;
    lightboxImg.src = galleryItems[index].img.replace('w=500','w=1400');
    lightboxImg.alt = galleryItems[index].caption;
    lightbox.classList.add('open');
    lightbox.setAttribute('aria-hidden','false');
  }
  function closeLightbox(){ lightbox.classList.remove('open'); lightbox.setAttribute('aria-hidden','true'); }
  function stepLightbox(dir){
    currentGalleryIndex = (currentGalleryIndex + dir + galleryItems.length) % galleryItems.length;
    lightboxImg.src = galleryItems[currentGalleryIndex].img.replace('w=500','w=1400');
    lightboxImg.alt = galleryItems[currentGalleryIndex].caption;
  }
  galleryGrid.addEventListener('click', e => {
    const item = e.target.closest('.gallery-item');
    if (item) openLightbox(Number(item.dataset.index));
  });
  document.getElementById('lightboxClose').addEventListener('click', closeLightbox);
  document.getElementById('lightboxPrev').addEventListener('click', () => stepLightbox(-1));
  document.getElementById('lightboxNext').addEventListener('click', () => stepLightbox(1));
  lightbox.addEventListener('click', e => { if (e.target === lightbox) closeLightbox(); });
  document.addEventListener('keydown', e => {
    if (!lightbox.classList.contains('open')) return;
    if (e.key === 'Escape') closeLightbox();
    if (e.key === 'ArrowLeft') stepLightbox(-1);
    if (e.key === 'ArrowRight') stepLightbox(1);
  });

  /* =========================================================
     RENDER: TESTIMONIALS CAROUSEL
     ========================================================= */
  const testimonials = content.testimonials;
  const testimonialTrack = document.getElementById('testimonialTrack');
  const testimonialDots = document.getElementById('testimonialDots');
  testimonialTrack.innerHTML = testimonials.map(t => `
    <div class="testimonial-card">
      <img class="testi-photo" src="${t.photo}" alt="${t.pet}" loading="lazy">
      <div>
        <div class="testi-stars">${'<i class="fa-solid fa-star"></i>'.repeat(t.rating)}</div>
        <p class="testi-story">"${t.story}"</p>
        <div class="testi-name">${t.name}</div>
        <div class="testi-pet">${t.pet}</div>
      </div>
    </div>
  `).join('');
  testimonialDots.innerHTML = testimonials.map((_,i) => `<button class="tdot ${i===0?'active':''}" data-index="${i}" aria-label="Go to testimonial ${i+1}"></button>`).join('');

  let testiIndex = 0;
  function goToTestimonial(i){
    testiIndex = (i + testimonials.length) % testimonials.length;
    testimonialTrack.style.transform = `translateX(-${testiIndex * 100}%)`;
    testimonialDots.querySelectorAll('.tdot').forEach((d,idx) => d.classList.toggle('active', idx===testiIndex));
  }
  document.getElementById('testiPrev').addEventListener('click', () => goToTestimonial(testiIndex-1));
  document.getElementById('testiNext').addEventListener('click', () => goToTestimonial(testiIndex+1));
  testimonialDots.addEventListener('click', e => {
    const dot = e.target.closest('.tdot');
    if (dot) goToTestimonial(Number(dot.dataset.index));
  });
  let testiAuto = setInterval(() => goToTestimonial(testiIndex+1), 6500);
  document.querySelector('.testimonial-carousel').addEventListener('mouseenter', () => clearInterval(testiAuto));

  /* =========================================================
     RENDER: TIPS
     ========================================================= */
  const tipsGrid = document.getElementById('tipsGrid');
  tipsGrid.innerHTML = content.tips.map(t => `
    <article class="tip-card" data-aos="fade-up">
      <div class="tip-icon"><i class="fa-solid ${t.icon}"></i></div>
      <div class="tip-body">
        <span class="tip-tag">${t.tag}</span>
        <h3>${t.title}</h3>
        <p>${t.excerpt}</p>
        <a href="#" class="text-link" data-download-note>Read More <i class="fa-solid fa-arrow-right"></i></a>
      </div>
    </article>
  `).join('');

  /* =========================================================
     RENDER: AWARDS
     ========================================================= */
  document.getElementById('awardsRow').innerHTML = content.awards.map(a => `
    <div class="award-badge"><i class="fa-solid ${a.icon}"></i> ${a.text}</div>
  `).join('');

  /* =========================================================
     RENDER: FAQ ACCORDION
     ========================================================= */
  const faqAccordion = document.getElementById('faqAccordion');
  faqAccordion.innerHTML = content.faq.map((f,i) => `
    <div class="accordion-item" data-index="${i}">
      <button class="accordion-trigger" aria-expanded="false">${f.q} <i class="fa-solid fa-chevron-down"></i></button>
      <div class="accordion-panel"><p>${f.a}</p></div>
    </div>
  `).join('');
  faqAccordion.addEventListener('click', e => {
    const trigger = e.target.closest('.accordion-trigger');
    if (!trigger) return;
    const item = trigger.closest('.accordion-item');
    const panel = item.querySelector('.accordion-panel');
    const isOpen = item.classList.contains('open');
    faqAccordion.querySelectorAll('.accordion-item').forEach(i => {
      i.classList.remove('open');
      i.querySelector('.accordion-panel').style.maxHeight = null;
      i.querySelector('.accordion-trigger').setAttribute('aria-expanded','false');
    });
    if (!isOpen) {
      item.classList.add('open');
      panel.style.maxHeight = panel.scrollHeight + 'px';
      trigger.setAttribute('aria-expanded','true');
    }
  });

  } catch (err) {
    console.error('Content rendering failed partway through — page shell (nav, cookie banner, modals, chat) will still work:', err);
  }

  /* =========================================================
     NAV: scroll shadow, mobile menu, active link
     ========================================================= */
  const siteNav = document.getElementById('siteNav');
  const hamburger = document.getElementById('hamburger');
  const navLinks = document.getElementById('navLinks');

  window.addEventListener('scroll', () => {
    siteNav.classList.toggle('scrolled', window.scrollY > 20);
    updateScrollProgress();
    updateBackToTop();
  });

  hamburger.addEventListener('click', () => {
    const isOpen = siteNav.classList.toggle('mobile-open');
    hamburger.classList.toggle('open', isOpen);
    hamburger.setAttribute('aria-expanded', isOpen);
  });
  navLinks.addEventListener('click', e => {
    if (e.target.tagName === 'A') {
      siteNav.classList.remove('mobile-open');
      hamburger.classList.remove('open');
    }
  });

  /* ---------- SCROLL PROGRESS (Vitals Trail) ---------- */
  const vitalsProgress = document.getElementById('vitalsProgress');
  function updateScrollProgress(){
    const h = document.documentElement;
    const scrolled = (h.scrollTop || document.body.scrollTop);
    const height = h.scrollHeight - h.clientHeight;
    vitalsProgress.style.width = height > 0 ? `${(scrolled/height)*100}%` : '0%';
  }

  /* ---------- BACK TO TOP ---------- */
  const backToTop = document.getElementById('backToTop');
  function updateBackToTop(){ backToTop.classList.toggle('show', window.scrollY > 500); }
  backToTop.addEventListener('click', () => window.scrollTo({ top:0, behavior:'smooth' }));

  /* =========================================================
     DARK MODE (in-memory only — no storage)
     ========================================================= */
  const darkModeToggle = document.getElementById('darkModeToggle');
  darkModeToggle.addEventListener('click', () => {
    document.body.classList.toggle('dark');
    const icon = darkModeToggle.querySelector('i');
    icon.classList.toggle('fa-moon');
    icon.classList.toggle('fa-sun');
  });

  /* ---------- LANGUAGE TOGGLE (mock) ---------- */
  const langToggle = document.getElementById('langToggle');
  const langLabel = langToggle.querySelector('.lang-label');
  langToggle.addEventListener('click', () => {
    langLabel.textContent = langLabel.textContent === 'EN' ? 'ES' : 'EN';
    showToastNote('Multi-language content is a demo toggle — connect a translation workflow before launch.');
  });

  /* =========================================================
     COUNTERS (animate on scroll into view)
     ========================================================= */
  const counterObserver = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        animateCounter(entry.target);
        counterObserver.unobserve(entry.target);
      }
    });
  }, { threshold: 0.4 });
  document.querySelectorAll('.counter-num').forEach(c => counterObserver.observe(c));

  function animateCounter(el){
    const target = Number(el.dataset.target);
    const duration = 1600;
    const start = performance.now();
    function tick(now){
      const progress = Math.min((now - start) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      el.textContent = Math.floor(eased * target).toLocaleString();
      if (progress < 1) requestAnimationFrame(tick);
      else el.textContent = target.toLocaleString();
    }
    requestAnimationFrame(tick);
  }

  /* =========================================================
     BOOKING FORM VALIDATION + SUCCESS MODAL
     ========================================================= */
  const bookingForm = document.getElementById('bookingForm');
  const successModal = document.getElementById('successModal');

  bookingForm.addEventListener('submit', e => {
    e.preventDefault();
    let valid = true;
    bookingForm.querySelectorAll('[required]').forEach(field => {
      const wrapper = field.closest('.form-field');
      if (!field.value.trim()) {
        wrapper.classList.add('error');
        valid = false;
      } else {
        wrapper.classList.remove('error');
      }
    });
    const emailField = document.getElementById('email');
    if (emailField.value && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(emailField.value)) {
      emailField.closest('.form-field').classList.add('error');
      valid = false;
    }
    if (!valid) return;

    const petName = document.getElementById('petName').value;
    document.getElementById('successMessage').textContent =
      `Thanks! We've received ${petName}'s appointment request and will confirm by phone or email within one business hour.`;
    openModal(successModal);
    bookingForm.reset();
  });

  /* =========================================================
     MODALS (generic open/close)
     ========================================================= */
  function openModal(modal){ modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); }
  function closeModal(modal){ modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); }

  document.querySelectorAll('[data-close-modal]').forEach(btn => {
    btn.addEventListener('click', () => closeModal(btn.closest('.modal')));
  });
  document.querySelectorAll('.modal').forEach(modal => {
    modal.addEventListener('click', e => { if (e.target === modal) closeModal(modal); });
  });
  document.addEventListener('keydown', e => {
    if (e.key === 'Escape') document.querySelectorAll('.modal.open').forEach(closeModal);
  });

  /* ---------- Virtual Tour Modal ---------- */
  const tourModal = document.getElementById('tourModal');
  const tourImage = document.getElementById('tourImage');
  const tourCaption = document.getElementById('tourCaption');
  let tourIndex = 0;
  function renderTour(){
    tourImage.src = tourStops[tourIndex].img;
    tourImage.alt = tourStops[tourIndex].caption;
    tourCaption.textContent = tourStops[tourIndex].caption;
  }
  document.getElementById('virtualTourBtn').addEventListener('click', () => { tourIndex = 0; renderTour(); openModal(tourModal); });
  document.getElementById('tourPrev').addEventListener('click', () => { tourIndex = (tourIndex - 1 + tourStops.length) % tourStops.length; renderTour(); });
  document.getElementById('tourNext').addEventListener('click', () => { tourIndex = (tourIndex + 1) % tourStops.length; renderTour(); });

  /* ---------- Patient Portal / Refill Modals ---------- */
  const portalModal = document.getElementById('portalModal');
  document.getElementById('portalBtn').addEventListener('click', () => {
    document.getElementById('portalModalTitle').innerHTML = '<i class="fa-solid fa-address-card"></i> Patient Portal';
    openModal(portalModal);
  });
  document.getElementById('refillBtn').addEventListener('click', () => {
    document.getElementById('portalModalTitle').innerHTML = '<i class="fa-solid fa-pills"></i> Prescription Refill';
    openModal(portalModal);
  });
  document.getElementById('portalForm').addEventListener('submit', e => {
    e.preventDefault();
    closeModal(portalModal);
    showToastNote('Demo only — this form isn\'t connected to a real patient portal yet.');
  });

  /* ---------- "Coming soon" download/careers links ---------- */
  document.querySelectorAll('[data-download-note]').forEach(a => {
    a.addEventListener('click', e => {
      e.preventDefault();
      showToastNote('This is a demo link — connect real downloads or blog pages before launch.');
    });
  });
  const careersLink = document.getElementById('careersLink');
  if (careersLink) careersLink.addEventListener('click', e => {
    e.preventDefault();
    showToastNote('Careers page coming soon — reach out at hello@fernwoodanimalhospital.example');
  });

  /* =========================================================
     NEWSLETTER FORMS
     ========================================================= */
  ['newsletterForm','footerNewsletterForm'].forEach(id => {
    const form = document.getElementById(id);
    if (!form) return;
    form.addEventListener('submit', e => {
      e.preventDefault();
      showToastNote('Thanks for subscribing! Watch your inbox for wellness reminders.');
      form.reset();
    });
  });

  /* =========================================================
     COOKIE BANNER (persisted — shows once, then stays dismissed)
     ========================================================= */
  const cookieBanner = document.getElementById('cookieBanner');
  const COOKIE_CONSENT_KEY = 'fernwood_cookie_consent';

  function getCookieConsent() {
    try { return localStorage.getItem(COOKIE_CONSENT_KEY); }
    catch (e) { return null; } // private browsing / storage blocked — banner will just show each visit
  }
  function setCookieConsent(value) {
    try { localStorage.setItem(COOKIE_CONSENT_KEY, value); }
    catch (e) { /* ignore — nothing we can do if storage is blocked */ }
  }

  function showCookieBanner() {
    cookieBanner.classList.add('show');
    cookieBanner.setAttribute('aria-hidden', 'false');
  }
  function dismissCookie(choice) {
    cookieBanner.classList.remove('show');
    cookieBanner.setAttribute('aria-hidden', 'true');
    setCookieConsent(choice);
  }

  if (!getCookieConsent()) {
    setTimeout(showCookieBanner, 1200);
  }
  document.getElementById('cookieAccept').addEventListener('click', () => dismissCookie('accepted'));
  document.getElementById('cookieDecline').addEventListener('click', () => dismissCookie('declined'));

  /* =========================================================
     AI CHAT WIDGET (scripted demo)
     ========================================================= */
  const chatToggle = document.getElementById('chatToggle');
  const chatPanel = document.getElementById('chatPanel');
  const chatMessages = document.getElementById('chatMessages');
  const chatForm = document.getElementById('chatForm');
  const chatInput = document.getElementById('chatInput');
  const chatSuggestions = document.getElementById('chatSuggestions');

  const chatQA = [
    { q:'hours', label:'What are your hours?', a:"We're open Mon–Fri 7:30am–7pm, Sat 8am–5pm, and Sun 9am–2pm. Our emergency line runs 24/7." },
    { q:'services', label:'What services do you offer?', a:'Everything from wellness exams and vaccines to surgery, dentistry, and emergency care — 22 services in total. Check the Services section above!' },
    { q:'booking', label:'How do I book an appointment?', a:'Scroll to the Book an Appointment section and fill out the short form — we confirm within one business hour.' },
    { q:'emergency', label:'What if this is an emergency?', a:'Call our 24/7 emergency line right away at (555) 019-9911 — don\'t wait to use this chat.' }
  ];

  chatToggle.addEventListener('click', () => {
    const isOpen = chatPanel.classList.toggle('open');
    chatPanel.setAttribute('aria-hidden', !isOpen);
  });
  document.getElementById('chatClose').addEventListener('click', () => {
    chatPanel.classList.remove('open');
    chatPanel.setAttribute('aria-hidden','true');
  });

  function renderChatSuggestions(){
    chatSuggestions.innerHTML = chatQA.map(item => `<button class="chat-chip" data-q="${item.q}">${item.label}</button>`).join('');
  }
  renderChatSuggestions();

  function addChatMessage(text, who){
    const div = document.createElement('div');
    div.className = `chat-msg ${who}`;
    div.textContent = text;
    chatMessages.appendChild(div);
    chatMessages.scrollTop = chatMessages.scrollHeight;
  }

  function respondTo(text){
    const lower = text.toLowerCase();
    let match = chatQA.find(item => lower.includes(item.q));
    if (!match) {
      if (lower.includes('price') || lower.includes('cost')) {
        addChatMessage('Pricing varies by service — our wellness plans start at $19/month. Want me to point you to the Wellness Programs section?', 'bot');
        return;
      }
      addChatMessage("I'm a simple demo assistant, so I can only answer a few basics — try asking about hours, services, booking, or emergencies!", 'bot');
      return;
    }
    addChatMessage(match.a, 'bot');
  }

  chatSuggestions.addEventListener('click', e => {
    const chip = e.target.closest('.chat-chip');
    if (!chip) return;
    const item = chatQA.find(q => q.q === chip.dataset.q);
    addChatMessage(item.label, 'user');
    setTimeout(() => respondTo(item.q), 450);
  });

  chatForm.addEventListener('submit', e => {
    e.preventDefault();
    const text = chatInput.value.trim();
    if (!text) return;
    addChatMessage(text, 'user');
    chatInput.value = '';
    setTimeout(() => respondTo(text), 500);
  });

  /* =========================================================
     TOAST NOTE (lightweight, in-memory)
     ========================================================= */
  function showToastNote(message){
    let toast = document.querySelector('.toast-note');
    if (!toast) {
      toast = document.createElement('div');
      toast.className = 'toast-note';
      toast.setAttribute('role','status');
      document.body.appendChild(toast);
    }
    toast.textContent = message;
    toast.classList.add('show');
    clearTimeout(toast._timer);
    toast._timer = setTimeout(() => toast.classList.remove('show'), 3800);
  }

  /* initial calls */
  updateScrollProgress();
  updateBackToTop();
});
